### ISSUE TITLE
what's the status of this project?

### ISSUE THREAD

**Issue by ghost** [SwiftAndroid/swift-jni#1]
Thanks for this awesome project, is there a roadmap or milestone?

**Comment by ephemer** [comment]
@haoxins, right now it's not being actively developed. I originally made this for an app which has now been released. Here's the story behind it: https://medium.com/@ephemer/why-we-put-an-app-in-the-android-play-store-using-swift-96ac87c88dfc#.r19j7d6j7

The roadmap would be to get it merged into the Android part of the Apple/swift repo as a module. As it is there are questions open as to how to best go about a module like this:
1. Does it even belong in apple/swift? (My opinion is yes: if you have swift on android you need JNI)
2. Should this be a basic wrapper than imports the C header only, instead of swiftifying the API? When I made this SwiftPM was nowhere near ready for the functionality, but maybe it's now possible to keep the in-repo implementation as a basic wrapper and have a separate and more directly updatable SwiftPM SwiftJNI module.
3. Can we use `apinotes` to swiftify the API instead of using swift shims? (Probably to a point, but JNI's pseudo-OOP structure makes this difficult to do well)

I'll probably look at this again after Swift 3 is officially released because that will require us to look at the app code again too
